title: "TypeScript"
summary: "TypeScriptのサマリー"
topics: ["TypeScript"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - settimeout
  - flatmap
  - array
  - string-obj
  - oop
  - try-catch
  - fetch-api
