title: "Firebase"
summary: ""
topics: [firebase]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - enviroment-setup
  - firestore
  - firestore-query
  - transaction-batch
  - firestore-security-rule
  - cloud-functions
  - cloud-storage-for-firebase
  - firebase-admin
