title: "Next.js（App Router）"
summary: "Summary"
topics: [nextjs]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - overview
  - reference
  - create-next-app
  - routing-terminology
  - navigation
  - static-dynamic-data-fetch
  - static-dynamic-rendering-route
  - cache
  - router-refresh
  - revalidate-path
