title: "データベース設計"
summary: "https://www.udemy.com/course/database-logic/"
topics: [db]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - key
  - constraints
  - normalized-form
  - er-diagram
