title: "Golang"
summary: "Golang関連をまとめたノート"
topics: [go]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - package-module
  - compile-and-execute
  - print
  - variables
  - basic-types
  - function
  - conditional-branch
  - loop
  - defer
  - pointers
  - pass-by-value-ref
  - structs
  - type-keyword
  - interface
  - arrays-slices
  - map
  - make
  - copy
  - stringer
  - error
  - byte-type
  - io-reader
