title: "Docker・k8s"
summary: "Dockerとk8sのサマリ"
topics: [docker]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - what-is-docker
  - how-docker-works
  - setup-docker
  - basic-operation
  - container-communication
  - docker-network
  - copy-file-betweem-container-and-host
  - mounting-volumes
  - container-to-image
  - exec-container
